# Stargus - Starcraft data extraction tool & launcher for the Stratagus engine
# Minimal Makefile build (no meson, no cmake, no ffmpeg, no ImageMagick).

CXX      ?= c++
CC       ?= cc
AR       ?= ar
CXXFLAGS ?= -O2 -g -std=c++17
CFLAGS   ?= -O2 -g
PREFIX   ?= /usr/local

PKG_CONFIG ?= pkg-config

# StormLib has no pkg-config file; locate it under common Homebrew prefixes.
STORM_PREFIX ?= $(shell \
	if [ -d /opt/homebrew/opt/stormlib ]; then echo /opt/homebrew/opt/stormlib; \
	elif [ -d /usr/local/opt/stormlib ]; then echo /usr/local/opt/stormlib; \
	elif [ -d /opt/local ]; then echo /opt/local; \
	else echo /usr/local; fi)

STORM_CFLAGS := -I$(STORM_PREFIX)/include
STORM_LIBS   := -L$(STORM_PREFIX)/lib -lstorm

PNG_CFLAGS  := $(shell $(PKG_CONFIG) --cflags libpng 2>/dev/null)
PNG_LIBS    := $(shell $(PKG_CONFIG) --libs libpng 2>/dev/null)
ZLIB_CFLAGS := $(shell $(PKG_CONFIG) --cflags zlib 2>/dev/null)
ZLIB_LIBS   := $(shell $(PKG_CONFIG) --libs zlib 2>/dev/null)

OBJDIR := build/obj

STRATAGUS_DIR := stratagus

# All library sources (everything under src/ except the two executables).
SOURCES     := $(shell find src -name '*.cpp' | sort)
LIB_SOURCES := $(filter-out src/startool.cpp src/stargus.cpp,$(SOURCES))
LIB_OBJECTS := $(LIB_SOURCES:%.cpp=$(OBJDIR)/%.o)

STARTOOL_OBJ := $(OBJDIR)/src/startool.o
STARGUS_OBJ  := $(OBJDIR)/src/stargus.o

INCLUDES := -Isrc -Isrc/dat -Isrc/kaitai -Isrc/tileset -Isrc/libgrp \
            -Ibuild -Isubprojects/nlohmann_json/single_include \
            $(STORM_CFLAGS) $(PNG_CFLAGS) $(ZLIB_CFLAGS)
DEFINES  := -DHAVE_CONFIG_H -DKS_STR_ENCODING_NONE

UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Darwin)
  ICONV_LIBS := -liconv
  ENGINE_PLATFORM_DEFINES := -DUSE_MAC -DHAVE_GETOPT -DHAVE_STRNLEN
else ifeq ($(UNAME_S),Linux)
  ENGINE_PLATFORM_DEFINES := -DUSE_LINUX -DHAVE_GETOPT -DHAVE_STRNLEN
  DL_LIBS := -ldl
endif

LIBS := $(STORM_LIBS) $(PNG_LIBS) $(ZLIB_LIBS) $(ICONV_LIBS)

all: startool stargus

# Compile the extraction tool + library objects.
$(OBJDIR)/%.o: %.cpp build/config.h
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) $(DEFINES) $(INCLUDES) -c $< -o $@

# Launcher: needs the Stratagus game-launcher header and path macros.
$(STARGUS_OBJ): src/stargus.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -Istratagus/gameheaders \
		-DDATA_PATH='"$(PREFIX)/share/games/stratagus/stargus"' \
		-DSCRIPTS_PATH='"$(PREFIX)/share/games/stratagus/stargus"' \
		-DSTRATAGUS_BIN='"stratagus"' \
		-DSOURCE_DIR='"$(CURDIR)"' \
		-c $< -o $@

startool: $(STARTOOL_OBJ) $(LIB_OBJECTS)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LIBS)

stargus: $(STARGUS_OBJ)
	$(CXX) $(CXXFLAGS) -o $@ $^

build/config.h:
	@mkdir -p build
	@echo '/* autogenerated by Makefile */' > $@
	@echo '#define PACKAGE_DATA_DIR "$(PREFIX)/share/stargus"' >> $@
	@echo '#define PACKAGE_SOURCE_DIR "$(CURDIR)"' >> $@

clean:
	rm -rf build startool stargus

.PHONY: all clean
